skip-tables = [
  "partman.*",
  "DentrixAscend.*",
  "OpenDental.*",
  "DentrixCore.*",
  "public.IntegrationJobAudit",
  "public.Event*",
]

[start]
name = "Organizations"
schema = "public"
rows_to_sample = 100

[[table]]
name = "table1"
schema = "schema_definition_for_table1"
rows_to_sample = 100

[[table]]
name = "table2"
schema = "schema_definition_for_table2"
rows_to_sample = 150
